### ISSUE TITLE
Missing functions/objects???

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [krother/python_testing_tutorial#4]
Hi,

I'm very much enjoying the tutorial. I'm currently writing a Jupyter notebook to accompany the tutorial for an online learning course. However, I'm having trouble running some of the tests. 

The related imports are in **test_fixtures.py** 
`from word_counter import TextBody`

Also in **test_another.py**
`from word_counter import TextBody, WordCounter`
which I assume ought to be 
`from mobydick.word_counter import TextBody, WordCounter` (?)

I cannot find any mention of TexBody or WordCounter in any of the modules. Sorry if I am missing something obvious, but please could you let me know what I'm doing wrong?

Thanks

**Comment by PeteCausey-Freeman** [comment]
Never mind. I have worked it out. Sorry

**Comment by PeteCausey-Freeman** [comment]
Ah, no I figured it out. Sorry, Thanks

**Comment by krother** [comment]
OK, great! I have simplified the code so that you can spend less time on understanding the classes and more on the actual testing.
